<?php include './includes/head.php'; ?>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">LensLore 📸</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item list">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item list">
          <a class="nav-link" href="#submit">upload-photo</a>
        </li>

        <?php if (is_user_logged_in()) { ?>
          <li class="nav-item list">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
        <?php } ?>

        <?php if (is_user_logged_in()) { ?>
          <li class="right nav-link logout-link button-logout">
            <a href="<?php echo logout_url(); ?>">Log out
            </a>
          </li>
        <?php } ?>
      </ul>
      </div>
    </div>
  </nav>


  <?php require_once "includes/init.php"; ?>

  <?php
  $page_title = "Photo Upload Form";
  define("MAX_FILE_SIZE", 1500000);

  $upload_feedback = array(
    "general_error" => false,
    "too_large" => false
  );

  if (isset($_POST["upload"])) {

    $title = trim($_POST["title"]);
    $description = trim($_POST["description"]);
    $date_posted = $_POST["date_posted"];
    $source_url = trim($_POST["source"]) ?: "";

    $upload = $_FILES["photo-file"];
    $form_valid = true;

    if ($upload["error"] == UPLOAD_ERR_OK) {
      $upload_file_name = basename($upload["name"]);
      $upload_file_ext = strtolower(pathinfo($upload_file_name, PATHINFO_EXTENSION));


      if (!in_array($upload_file_ext, ['jpg'])) {
        $form_valid = false;
        $upload_feedback["general_error"] = true;
      }
    } else {
      // Other err
      $form_valid = false;
      $upload_feedback["general_error"] = true;
    }

    if ($form_valid) {
      $sql = "INSERT INTO photo_entries (title, description, date_posted, file_name, file_ext, source) VALUES (:title, :description, :date_posted, :file_name, :file_ext, :source)";
      $params = array(
        ':title' => $title,
        ':description' => $description,
        ':date_posted' => $date_posted,
        ':file_name' => $upload_file_name,
        ':file_ext' => $upload_file_ext,
        ':source' => $source_url
      );

      $result = exec_sql_query($db, $sql, $params);
      if ($result) {
        $photo_id = $db->lastInsertId("id");
        $upload_storage_path = "public/uploads/photo_entries/" . $photo_id . "." . $upload_file_ext;

        if (!move_uploaded_file($upload["tmp_name"], $upload_storage_path)) {
          error_log("Failed to store uploaded file.");
        }
      }
    }
  }
  ?>
  <?php include "includes/hero.php"; ?>
  <div class="hor-flex">
    <div class="hor">
      <div class="container">
        <p>The seed data used to populate the db was generated by CHATGPT</p>
        <p>I am a passionate photographer with a love for capturing moments. Here's a glimpse into my world: </p>
      </div>
      <div class="row five-cols padding">
        <?php
        $tags = exec_sql_query($db, 'SELECT * FROM tags')->fetchAll();
        foreach ($tags as $tag) {
          $tag_id = $tag['id'];
          $tag_name = $tag['name'];
          include "includes/tag-tile.php";
        }
        ?>
      </div>
    </div>
  </div>
  <main class="main">
    <section class="portfolio my-5">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
          <?php
          $currentTagName = $_GET['tag'] ?? null;
          if ($currentTagName !== null) {
            $photosQuery = "SELECT photo_entries.* FROM photo_entries
                    INNER JOIN photo_tags ON photo_entries.id = photo_tags.photo_entries_id
                    INNER JOIN tags ON photo_tags.tag_id = tags.id
                    WHERE tags.name = :tag_name";
            $allPhotos = exec_sql_query($db, $photosQuery, [':tag_name' => $currentTagName])->fetchAll();
          } else {
            $photosQuery = "SELECT * FROM photo_entries";
            $allPhotos = exec_sql_query($db, $photosQuery)->fetchAll();
          }
          foreach ($allPhotos as $photo) {
            $query = http_build_query(['id' => $photo['id']]);
            $photoDetailsUrl = "/details?" . $query;
            include "includes/photo-card.php";
          }
          ?>
        </div>
      </div>
    </section>

    <div class="container mt-4 photo-container">
      <h3 class="photo-title" id="submit">Submit a Photo</h3>
      <form action="/" method="post" enctype="multipart/form-data" class="needs-validation editpage">
        <input type="hidden" name="MAX_FILE_SIZE" value="1500000">

        <div class="alert alert-danger" style="display: <?= $upload_feedback['too_large'] ? 'block' : 'none'; ?>">
          We're sorry. The file failed to upload because it was too big. Please select a file that's no larger than 1.5MB.
        </div>
        <div class="alert alert-danger" style="display: <?= $upload_feedback['general_error'] ? 'block' : 'none'; ?>">
          We're sorry. Something went wrong. Please select a JPG file to upload.
        </div>

        <!-- Photo Title -->
        <div class="form-group">
          <label for="photo-title" class="form-label strong">Photo Title:</label>
          <input type="text" class="form-control" id="photo-title" name="title">
          <div class="invalid-feedback">Photo title is required.</div>
        </div>

        <!-- Photo Description -->
        <div class="form-group">
          <label for="photo-description" class="form-label strong">Photo Description:</label>
          <textarea class="form-control" id="photo-description" name="description"></textarea>
          <div class="invalid-feedback">Description is required.</div>
        </div>

        <!-- Date Posted -->
        <div class="form-group">
          <label for="date-posted" class="form-label strong">Date Posted:</label>
          <input type="date" class="form-control" id="date-posted" name="date_posted">
          <div class="invalid-feedback">Date posted is required.</div>
        </div>

        <!-- Photo File -->
        <div class="form-group">
          <label for="upload-file" class="form-label strong">Photo File:</label>
          <input type="file" class="form-control-file" id="upload-file" name="photo-file" accept=".jpg">
          <div class="invalid-feedback">A photo file is required.</div>
        </div>

        <!-- Source URL -->
        <div class="form-group">
          <label for="upload-source" class="form-label strong">Source URL (optional):</label>
          <input type="url" class="form-control" id="upload-source" name="source" placeholder="URL where found">
        </div>

        <!-- Submit Button -->
        <div class="form-group">
          <button type="submit" name="upload" class="btn btn-primary ">Upload Photo</button>
        </div>
      </form>
    </div>
  </main>

  <?php include "includes/bootstrapJS-CDN.php"; ?>
</body>

</html>
